name: Integración y entrega continua

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      nombres: "Hector_David"
      apellidos: "Paredes_Garcia"
      edad: "32"
      version_proyecto: "3.0"

    steps:
      - name: presentación
        run: |
          echo "Nombres: $nombres"
          echo "Apellidos: $apellidos"
          echo "Edad: $edad"

      - name: datos generales
        run: echo "carrera de ingeniería de sistemas"

      - name: variables de entorno secretas
        env:
          user: ${{ secrets.user }}
          password: ${{ secrets.password }}
        run: |
          echo "user: ******"
          echo "password: ******"

      - name: variables abiertas
        run: |
          echo "Versión del proyecto: $version_proyecto"

      - name: Verificar secrets
        run: |
            if [ -z "${{ secrets.user }}" ]; then
            echo "USER está vacío o no existe"
            else
            echo "USER está configurado correctamente"
            fi

            if [ -z "${{ secrets.password }}" ]; then
            echo "PASSWORD está vacío o no existe"
            else
            echo "PASSWORD está configurado correctamente"
            fi

